server:
  port: 8765

spring:
  application:
    name: ApiGateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: CarPick1_root
          uri: http://localhost:8081
          predicates:
            - Path=/
        - id: CarPick1_decode
          uri: http://localhost:8081
          predicates:
            - Path=/decode
        - id: CarPick1_toPart
          uri: http://localhost:8081
          predicates:
            - Path=/toPart
        - id: CarPickKia1_root
          uri: http://localhost:8082
          predicates:
            - Path=/
        - id: CarPickKia1_decode
          uri: http://localhost:8082
          predicates:
            - Path=/decodeKia
        - id: CarPickKia1_toPart
          uri: http://localhost:8082
          predicates:
            - Path=/toPartKia